language: swift
osx_image: xcode8.2

before_install:
  - gem install xcpretty

script:
 - set -o pipefail && xcodebuild -project 'KataLogInLogOut.xcodeproj' -scheme 'KataLogInLogOut' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6' clean test build CODE_SIGN_IDENTITY=- | xcpretty -c